### ISSUE TITLE
javascript `var` and `function` are keywords

### ISSUE THREAD

**Issue by MetaMemoryT** [atom/solarized-light-syntax#10]
The javascript `var' and `function' are not highlighting. See:

https://github.com/atom/solarized-dark-syntax/pull/23

https://github.com/atom/language-javascript/issues/47

https://github.com/atom/solarized-dark-syntax/issues/21

**Comment by chrisyip** [comment]
Looks like it's not solved yet:

![screen shot 2015-02-28 at 9 36 36 pm](https://cloud.githubusercontent.com/assets/189559/6426374/0b870198-bf92-11e4-89c2-e4961f5cb464.png)
![screen shot 2015-02-28 at 9 36 51 pm](https://cloud.githubusercontent.com/assets/189559/6426375/0bbc2562-bf92-11e4-9433-a610caf4f2c4.png)

Atom 0.184.0 and solarized-light-syntax 0.19.0.
