### ISSUE TITLE
lua build-in function are not have different colors to user functions.

### ISSUE THREAD

**Issue by xpol** [atom/solarized-light-syntax#20]

**Comment by lee-dohm** [comment]
Does the [language-lua package](https://atom.io/packages/language-lua) differentiate between the two? Most likely, this is a bug in the language package, not the theme.

**Comment by xpol** [comment]
Switch theme to atom-material-syntax will display different color:
solarized-light-syntax:

![image](https://cloud.githubusercontent.com/assets/20248/13371746/5e89776e-dd68-11e5-8228-ee0014e59231.png)

atom-material-syntax:

![image](https://cloud.githubusercontent.com/assets/20248/13371745/41aa6d60-dd68-11e5-925a-385d5c7e4cd2.png)

**Comment by simurai** [comment]
This seems to be fixed. Currently renders as:

![image](https://user-images.githubusercontent.com/378023/44570133-c291f800-a7b7-11e8-913b-e88e68ad7144.png)
