### ISSUE TITLE
Bracket highlighting is partially borken

### ISSUE THREAD

**Issue by samu** [atom/solarized-light-syntax#44]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Bracket highlighting is partially broken. Bracket pairs which open and close on the same line will not be highlighted at all: 

![screen shot 2018-10-27 at 2 00 01 pm](https://user-images.githubusercontent.com/1936709/47603728-7c902500-d9f0-11e8-8304-61ff2036e271.png)

Pairs which span multiple lines are not highlighted on the bracket on which the cursor lies:

![screen shot 2018-10-27 at 1 57 13 pm](https://user-images.githubusercontent.com/1936709/47603718-64b8a100-d9f0-11e8-90a0-25afbc981550.png)

### Steps to Reproduce

1. run atom in save mode
2. create file: 
```
{}
{

}
```
3. place cursor accordingly

**Expected behavior:**

Both brackets are highlighted.

**Actual behavior:**

Both brackets are not highlighted.

**Reproduces how often:**

100%

### Versions

 1.32.0

### Additional Information
I tried other themes which seem to work fine.

**Comment by Arcanemagus** [comment]
Confirming on WIndows 10 with:
```
Atom    : 1.34.0-nightly4
Electron: 2.0.11
Chrome  : 61.0.3163.100
Node    : 8.9.3
apm  2.1.3
npm  6.2.0
node 8.9.3 x64
atom 1.34.0-nightly4
python 2.7.15
git 2.19.1.windows.1
visual studio 2015
```

**Comment by simurai** [comment]
@samu Thanks for reporting. 🙇 

This is caused by the cursor-line being on top of the bracket matcher highlights. PR #45 changes the cursor-line to be semi-transparent so that the bracket matcher can be seen underneath.
